### ISSUE TITLE
Questo progetto è abbandonato?

### ISSUE THREAD

**Issue by andreadelfante** [italia/spid-ios-sdk#3]
Ciao a tutti,

avrei bisogno di una info, questo progetto è ancora in fase di sviluppo?
Dato che entro il 28 Febbraio 2021 tutti i siti di PA devono fornire accesso con SPID, avrei bisogno di utilizzare questa libreria per implementare su piattaforma iOS la login tramite SPID.

Ho visto che attualmente le chiamate puntano ad un endpoint che fornisce dati stubbed.

Grazie in anticipo!

**Comment by peppelinux** [comment]
Abbiamo ricevuto alcune segnalazioni da parte degli sviluppatori che ci indicano che questo repository conterrebbe risorse 
non allineate con lo stato attuale delle Specifiche SPID.

Spero di ottenere un tuo gentile feedback entro la prossima settimana,
Grazie e a presto

**Comment by vivadaniele** [comment]
il progetto fu realizzato nella circostanza dell’hackday. Successivamente non fu più evoluto.
